lang: cpp
dist: xenial
compiler: gcc
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake-data
      - cmake
      - libsdl2-dev
      - qt5-default
      - bison

before_script:
  - sudo add-apt-repository ppa:rexut/recoil -y
  - sudo apt-get update -
  - sudo apt-get install boost1.63

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8
  - make
  - ctest .
