dist: xenial
compiler: gcc
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake-data
      - cmake
      - libsdl2-dev
      - qt5-default
      - boost-all-dev
      - bison


script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8
  - make
