trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    choco install llvm --yes
  displayName: 'install llvm'
- script: |
    vcpkg install sdl2
  displayName: 'vcpkg install'
- script: |
    mkdir build
    cd build
    cmake -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DFRONT_END=qt -T"llvm" ..
    cmake --build .
  displayName: 'cmake'