trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  submodules: true
- script: |
    pip install aqtinstall
    C:
    cd \
    mkdir Qt
    cd Qt
    aqtinst 5.11.3 windows win64_msvc2017_64
  displayName: 'install qt'
- script: |
    choco install llvm ninja winflexbison3 --yes
    set PATH=C:\Program Files\LLVM\bin;%PATH%
    clang-cl --version    
  displayName: 'install llvm, ninja, bison'
#- script: |
#    vcpkg install sdl2
#  displayName: 'vcpkg install'
- script: |
    set PATH=C:\Program Files\LLVM\bin;%PATH%
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    mkdir build
    cd build
    cmake -G Ninja ^
      -DCMAKE_BUILD_TYPE=Release ^
      -DCMAKE_C_COMPILER=clang-cl ^
      -DCMAKE_CXX_COMPILER=clang-cl ^
      -DFRONT_END=qt ^
      -DBISON_COMMAND=win_bison ^
      -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake ^
      ..
    cmake --build .
  displayName: 'cmake'
#
